archeryscorepad/archeryscorepad/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'score'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('score.urls'),)
]

archeryscorepad/score/urls.py
from django.urls import path
from score import views

app_name = 'score'

urlpatterns=[
    path("", views.index, name="index"),
    path("registration", views.registration, name="registration"),      
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("myprofile/<int:id>", views.myprofile, name="myprofile"), 
    path("registration/<int:pk>/edit/", views.edit_profile, name='edit_profile'),  
    path("round/<int:id>", views.round, name="round"), 
    path("addscore", views.addscore, name="addscore"),
    path("clubscores/<int:id>", views.clubscores, name="clubscores"),    
    path("roundscores", views.roundscores, name="roundscores"),
    path("displayroundscores/<int:id>", views.displayroundscores, name="displayroundscores"),
    path("scores/<int:id>", views.scores, name="scores"),
    path("myscores/<int:id>", views.myscores, name="myscores"),
    path("addaclub", views.addaclub, name="addaclub"),
    path("addscorecard/<int:pk>", views.addscorecard, name="addscorecard"),
    #path("addscorecard", views.addscorecard, name="addscorecard"),
    path("readscorecard/<int:id>", views.readscorecard, name="readscorecard"),
]

archeryscorepad/score/models.py
from csv import list_dialects
from operator import is_not
from queue import Empty
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.core.validators import MaxValueValidator
from django.db.models import Sum, Count, Avg
from django.db.models.deletion import CASCADE
from django.utils import timezone
from datetime import datetime

class ProfileUser(AbstractUser):
    GENDER_CHOICES = (
        ('F', 'Female',),
        ('M', 'Male',),
    )
    gender = models.CharField(max_length=1, default="M", choices=GENDER_CHOICES)
    DoB = models.DateField(verbose_name="Date of Birth", null=True, help_text="Date of Birth must take the form dd/mm/yyyy")
    club = models.ForeignKey('club', null=True, blank=True, on_delete=models.CASCADE)

    def calculate_age(self):
        return int((datetime.now().date() - self.DoB).days / 365.25)
    age = property(calculate_age) 

    def calculate_shootingas(self):
        if self.gender == 'F':
            if self.age >= 18:
                return 1
            elif self.age <= 18 and self.age >= 17:
                return 2
            elif self.age <= 16 and self.age >= 15:
                return 3
            elif self.age <= 14 and self.age >= 13 :
                return 4
            elif self.age <= 12:
                return 5
        if self.gender == 'M':
            if self.age >= 18:
                return 6
            elif self.age <= 18 and self.age >= 17:
                return 7
            elif self.age <= 16 and self.age >= 15:
                return 8
            elif self.age <= 14 and self.age >= 13:
                return 9
            elif self.age <= 12:
                return 10
    shooting = property(calculate_shootingas)



class BowType(models.Model) :

    bowtype = models.CharField(max_length=10)

    def __str__(self):
        return str(self.bowtype)

class Round(models.Model):
    roundname = models.CharField(max_length=200)
    maxscore = models.IntegerField(default=0)
    type = models.CharField(max_length=1, default='M')
    numberOfEnds = models.IntegerField(default=0)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return str(self.roundname)

#class RoundType(models.Model):
#    rndtype = models.CharField(max_length=7)

#    def __str__(self):
#        return str(self.rndtype)


class Age(models.Model):
    ageband = models.CharField(max_length=14)
    maxage = models.IntegerField(verbose_name="Age Range")
    gender = models.CharField(max_length=1)

    def __str__(self):
        return str(self.ageband)

class Classification(models.Model):
    age = models.ForeignKey('Age', related_name='shooting', on_delete=models.CASCADE)
    bowtype = models.ForeignKey("BowType", verbose_name='bows', on_delete=models.CASCADE) 
    roundname = models.ForeignKey('Round', verbose_name='round', on_delete=models.CASCADE)   
#    round = models.ForeignKey('RoundType', related_name='roundtype', on_delete=models.CASCADE)
    third = models.CharField(max_length=4, verbose_name="3rd Class Bowman", null=True, blank=True)
    second = models.CharField(max_length=4, verbose_name="2nd Class Bowman",  null=True, blank=True)
    first = models.CharField(max_length=4, verbose_name="1st Class Bowman",  null=True, blank=True)
    BM = models.CharField(max_length=4, verbose_name="Bowman",  null=True, blank=True)
    MB = models.CharField(max_length=4, verbose_name="Master Bowman",  null=True, blank=True)
    GMB = models.CharField(max_length=4, verbose_name="Grand Master Bowman",  null=True, blank=True)
    classindex = models.CharField(max_length=5, null=True)

    class Meta:
        ordering = ['bowtype', 'age', 'id']

    def index(self):
        return str(self.age.ageband)+ ' ' +str(self.bowtype.bowtype)+ ' ' +str(self.roundname.roundname)
    index = property(index) 

    def save(self, *args, **kwargs):
       self.classindex = self.index  
       super(Classification, self).save(*args, **kwargs)   

    def __str__(self):
        return self.index + ' ' + str(self.classindex)


class Handicap(models.Model): 
    handicap = models.IntegerField(primary_key=True)
    WA1440_Gents = models.IntegerField(default='', blank=True, null=True)
    WA1440_Ladies = models.IntegerField(default='', blank=True, null=True)
    Half_WA1440_Gents = models.IntegerField(default='', blank=True, null=True)
    Half_WA1440_Ladies = models.IntegerField(default='', blank=True, null=True)
    Metric_I = models.IntegerField(default='', blank=True, null=True)
    Metric_II = models.IntegerField(default='', blank=True, null=True)
    Metric_III = models.IntegerField(default='', blank=True, null=True)
    Metric_IV = models.IntegerField(default='', blank=True, null=True)
    Metric_V = models.IntegerField(default='', blank=True, null=True)
    Long_Metric_Gents = models.IntegerField(default='', blank=True, null=True)
    Long_Metric_Ladies = models.IntegerField(default='', blank=True, null=True)
    Long_Metric_II = models.IntegerField(default='', blank=True, null=True)
    Long_Metric_III = models.IntegerField(default='', blank=True, null=True)
    Long_Metric_IV = models.IntegerField(default='', blank=True, null=True)
    Long_Metric_V = models.IntegerField(default='', blank=True, null=True)
    Short_Metric = models.IntegerField(default='', blank=True, null=True)
    Short_Metric_II = models.IntegerField(default='', blank=True, null=True)
    Short_Metric_III = models.IntegerField(default='', blank=True, null=True)
    Short_Metric_IV = models.IntegerField(default='', blank=True, null=True)
    Short_Metric_V = models.IntegerField(default='', blank=True, null=True)
    WA_900 = models.IntegerField(default='', blank=True, null=True)
    WA_70M = models.IntegerField(default='', blank=True, null=True)
    WA_60M = models.IntegerField(default='', blank=True, null=True)
    WA_50M = models.IntegerField(default='', blank=True, null=True)
    WA_Standard_Bow = models.IntegerField(default='', blank=True, null=True)
    Olympic_Match = models.IntegerField(default='', blank=True, null=True)
    York = models.IntegerField(default='', blank=True, null=True)
    Hereford = models.IntegerField(default='', blank=True, null=True)
    Bristol_II = models.IntegerField(default='', blank=True, null=True)
    Bristol_III = models.IntegerField(default='', blank=True, null=True)
    Bristol_IV = models.IntegerField(default='', blank=True, null=True)
    Bristol_V = models.IntegerField(default='', blank=True, null=True)
    St_George = models.IntegerField(default='', blank=True, null=True)
    Albion = models.IntegerField(default='', blank=True, null=True)
    Windsor = models.IntegerField(default='', blank=True, null=True)
    Short_Windsor = models.IntegerField(default='', blank=True, null=True)
    Junior_Windsor = models.IntegerField(default='', blank=True, null=True)
    Short_Junior_Windsor = models.IntegerField(default='', blank=True, null=True)
    New_Western = models.IntegerField(default='', blank=True, null=True)
    Long_Western = models.IntegerField(default='', blank=True, null=True)
    Western = models.IntegerField(default='', blank=True, null=True)
    Short_Western = models.IntegerField(default='', blank=True, null=True)
    Junior_Western = models.IntegerField(default='', blank=True, null=True)
    Short_Junior_Western = models.IntegerField(default='', blank=True, null=True)
    American = models.IntegerField(default='', blank=True, null=True)
    St_Nicholas = models.IntegerField(default='', blank=True, null=True)
    New_National = models.IntegerField(default='', blank=True, null=True)
    Long_National = models.IntegerField(default='', blank=True, null=True)
    National = models.IntegerField(default='', blank=True, null=True)
    Short_National = models.IntegerField(default='', blank=True, null=True)
    Junior_National = models.IntegerField(default='', blank=True, null=True)
    Short_Junior_National = models.IntegerField(default='', blank=True, null=True)
    New_Warwick = models.IntegerField(default='', blank=True, null=True)
    Long_Warwick = models.IntegerField(default='', blank=True, null=True)
    Warwick = models.IntegerField(default='', blank=True, null=True)
    Short_Warwick = models.IntegerField(default='', blank=True, null=True)
    Junior_Warwick = models.IntegerField(default='', blank=True, null=True)
    Short_Junior_Warwick = models.IntegerField(default='', blank=True, null=True)
 
    class Meta:
        ordering = ['handicap']

    def __str__(self):
        return str(self.handicap) 


class Score(models.Model):
    archer = models.ForeignKey('ProfileUser', on_delete=CASCADE)
    rndname = models.ForeignKey('Round', related_name='round', on_delete=CASCADE)
    shootingas = models.ForeignKey('Age', related_name='shootingas', on_delete=models.CASCADE)
    bowtype = models.ForeignKey('BowType', related_name='bowtypes', default=1, on_delete=CASCADE)
    score = models.IntegerField(default=0, blank=True)
    classification = models.CharField(max_length=6, blank=True, null=True)
    handicap = models.IntegerField(default=0, blank=True, null=True)
    cumulativeHandicap = models.IntegerField(default=0, blank=True, null=True)
    dateshot = models.DateField(verbose_name="Date Round Shot", default=timezone.now)
    created_date = models.DateTimeField(default=timezone.now)
    classid = models.IntegerField(default=0)

    def classify(self):
        z = self.classid
        a = Classification.objects.filter(classindex=self.classid).values_list('third', flat=True).last()
        b = Classification.objects.filter(classindex=self.classid).values_list('second', flat=True).last()
        c = Classification.objects.filter(classindex=self.classid).values_list('first', flat=True).last()
        d = Classification.objects.filter(classindex=self.classid).values_list('BM', flat=True).last()
        e = Classification.objects.filter(classindex=self.classid).values_list('MB', flat=True).last()

archeryscorepad/score/forms.py
from django import forms
from .models import ProfileUser, Score, club, roundscore
from django.forms import ModelForm, TextInput
from score.models import ProfileUser, Score, club
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.forms import UserCreationForm
from bootstrap_datepicker_plus import DatePickerInput

class RegistrationForm(UserCreationForm):

    class Meta:
        model = ProfileUser
        fields = (
            'username',
            'first_name',
            'last_name',
            'club',
            'email',
            'gender',
            'DoB',
            'password1',
            'password2',
        )
        widgets = {'DoB': DatePickerInput(format='%d/%m/%Y')}
        help_texts = {
            'password1': None,
        }

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.gender = self.cleaned_data['gender']
        user.DoB = self.cleaned_data['DoB']
        if commit:
            user.save()

        return user


class ScoreForm(forms.ModelForm):

    class Meta:
        model = Score
        fields = [
            'rndname',
            'bowtype',
            'dateshot',
            'score'
        ]
        widgets = {'dateshot' : DatePickerInput(format='%d/%m/%Y')}

class AddClubForm(forms.ModelForm):
    class Meta:
        model = club
        fields = [
            'club_name',
            'region'
        ]

class AddRoundScore(forms.ModelForm):
    class Meta:
        model = roundscore
        fields = [
            'shot_1',
            'shot_2',
            'shot_3',
            'shot_4',
            'shot_5',
            'shot_6',
            'shot_7',
            'shot_8',
            'shot_9',
            'shot_10',
            'shot_11',
            'shot_12'
        ]
        widgets = {
            'shot_1': TextInput(attrs={'':''}),
            'shot_2': TextInput(attrs={'':''}),
            'shot_3': TextInput(attrs={'':''}),
            'shot_4': TextInput(attrs={'':''}),
            'shot_5': TextInput(attrs={'':''}),
            'shot_6': TextInput(attrs={'':''}),
            'shot_7': TextInput(attrs={'':''}),
            'shot_8': TextInput(attrs={'':''}),
            'shot_9': TextInput(attrs={'':''}),
            'shot_10': TextInput(attrs={'':''}),
            'shot_11': TextInput(attrs={'':''}),
            'shot_12': TextInput(attrs={'':''}),
        }

archeryscorepad/score/templates/score/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Archery Score Pad{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'score/favicon.ico' %}"/>
        <link href="{% static 'score/styles.css' %}" rel="stylesheet">     
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>


{% block extrahead %}
{% endblock %}
    </head>
    <body>
<div class="container-fluid">
<div class="row">
    <div class="sidebar col-lg-2 col-md-3 p-3">

        <h3>Archery Score Pad</h3>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username|title }}</strong>
            {% else %}
                Not signed in.
            {% endif %}
        </div>
<hr class="style1">

            {% block nav %}        
            {% if user.is_authenticated %}

                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:index' %}">Home</a></h5>
                </div>                
                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:myprofile' user.id %}">My Profile</a></h5>
                </div>                  
                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:myscores' user.id %}">My Records</a></h5>
                </div>                   
                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:addscore' %}">Add a score</a></h5>
                </div>
                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:clubscores' user.club_id %}">Club Scores</a></h5>
                </div>
                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:roundscores' %}">Round Scores</a></h5>
                </div>

                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:logout' %}">Log Out</a></h5>
                </div>


            {% if user.is_staff %}

                <button class="btn btn-outline-danger btn-block" data-toggle="dropdown" >
                  Site Admin
                </button>
                <div class="dropdown-menu dropdown-menu-lg-right">
                    <a class="dropdown-item" href="{% url 'score:addaclub' %}">Add a Club</a>
                    <a class="dropdown-item" href="#">Add a Classification</a>
                    <a class="dropdown-item" href="#">Add a Handicap</a>
                </div>

            {% endif %}
            {% else %}
                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:login' %}">Log In</a></h5>
                </div>
                <div>
                    <h5><a class="btn btn-outline-dark btn-block" href="{% url 'score:registration' %}">Register</a></h5>
                </div>

            {% endif %}


<p class="small"><a href="mailto:admin@admin.com">Click here</a> to contact the site admin</p>
            {% endblock %}
        </div>
            <div class="main col-lg-10 col-md-9 p-5">
                {% block body %}
                {% endblock %}
            </div>
    </div>
</div>
</div>

<script>
var dropdownElementList = [].slice.call(document.querySelectorAll('.dropdown-toggle'))
var dropdownList = dropdownElementList.map(function (dropdownToggleEl) {
  return new bootstrap.Dropdown(dropdownToggleEl)
})
</script>
    </body>
</html>

archeryscorepad/score/templates/score/layoutsafe.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Archery Score Pad{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'score/favicon.ico' %}"/>
        <link href="{% static 'score/styles.css' %}" rel="stylesheet">     
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>


{% block extrahead %}
{% endblock %}
    </head>
    <body>

        <h1>Archery Score Pad</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username|title }}</strong>
            {% else %}
                Not signed in.
            {% endif %}
        </div>

        <ul class="nav">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <h2><a class="nav-link badge badge-light" href="{% url 'score:myprofile' user.id %}">My Profile</a></h2>
                </li>                                    
                <li class="nav-item">
                    <h2><a class="nav-link badge badge-light" href="{% url 'score:addscore' %}">Add a score</a></h2>
                </li>
                <li class="nav-item">
                    <h2><a class="nav-link badge badge-light" href="{% url 'score:clubscores' %}">Club Scores</a></h2>
                </li>
                <li class="nav-item">
                    <h2><a class="nav-link badge badge-light" href="{% url 'score:roundscores' %}">Round Scores</a></h2>
                </li>
                <li class="nav-item">
                    <h2><a class="nav-link badge badge-light" href="{% url 'score:logout' %}">Log Out</a></h2>
                </li>
            {% if user.is_staff %}
            <li class="nav-item">
                <h2><a class="nav-link badge badge-light" href="{% url 'score:site_admin' %}">Site Admin</a></h2>
            </li>
            {% endif %}
            {% else %}
                <li class="nav-item">
                    <h2><a class="nav-link badge badge-light" href="{% url 'score:login' %}">Log In</a></h2>
                </li>
                <li class="nav-item">
                    <h2><a class="nav-link badge badge-light" href="{% url 'score:registration' %}">Register</a></h2>
                </li>

            {% endif %}
        </ul>
        <hr>

        {% block body %}
        {% endblock %}
<script>
var dropdownElementList = [].slice.call(document.querySelectorAll('.dropdown-toggle'))
var dropdownList = dropdownElementList.map(function (dropdownToggleEl) {
  return new bootstrap.Dropdown(dropdownToggleEl)
})
</script>
    </body>
</html>

archeryscorepad/score/templates/score/login.html
{% extends "score/layout.html" %}

{% block body %}

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'score:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username (Case Sensitive)">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'score:registration' %}">Register here.</a>

{% endblock %}

archeryscorepad/score/templates/score/myprofile.html
{% extends "score/layout.html" %}
{% load static %}

{% block body %}
{% if user.is_authenticated %}

<div class="container">


  <ul class="list-unstyled row">
    <li class="list-group-item list-group-item-dark col-md-12"><h2>Archery Profile</h2></li>
    <li class="list-group-item col-md-6"><b>Name:</b> {{ user.first_name }} {{ user.last_name }}</li>
    <li class="list-group-item col-md-6"><b>Username:</b> {{ user.username }} </li>
    <li class="list-group-item col-md-6"><b>Club:</b> {{ user.club }}</li>
    <li class="list-group-item col-md-6"><b>EMail:</b> {{ user.email }} </li>
    <li class="list-group-item col-md-6"><b>Date of Birth:</b> {{ user.DoB }} </li>
    <li class="list-group-item col-md-6"><b>Gender:</b> {{ user.get_gender_display }}</li>
    <li class="list-group-item col-md-6"><b>Age:</b> {{ user.age }} </li>
    <li class="list-group-item col-md-6"><b>Shooting as:</b>  {% for rnd in rnds %}
                                                        {% if user.shooting == rnd.id%}
                                                            {{ rnd.ageband }}
                                                        {% endif %}
                                                      {% endfor %}</li>
    <li class="list-group-item col-md-6"><b>Handicap:</b>  {% for post in cumHcap %}
                                                              {% if forloop.last %}
                                                                  {{ post.cumulativeHandicap}} 
                                                              {% endif %}
                                                            {% endfor %}</li>                                                      
     <li class="list-group-item col-md-6"><b>Current Classification:</b> 
                                                          {% for object in classification %}
                                                          
                                                            {% if forloop.first %}
                                                              {{ classification }}
                                                            {% endif %}
                                                                                                                                                                       
                                                          {% endfor %} </li>
    </ul>

<br>

  <ul class="list-unstyled row">
    <li class="list-group-item list-group-item-dark col-md-12"><h2>Rounds Shot</h2></li>  
    {% for post in posts %}
    
          <a href="{% url 'score:scores' post.rndname__id %}" ><li class="list-group-item col-md-6"><b>Round Name:</b> {{ post.rndname__roundname }}</a>
          <p class="card-text"><small class="text-muted">Times Shot: {{ post.rndname__count }}</small></p></li>
      {% empty %}
        <div class="alert alert-info" role="alert">
          No rounds recorded yet!
        </div>
    {% endfor %}
  </ul>

</div>
{% endif %}
{% endblock %}

archeryscorepad/score/templates/score/myscores.html
{% extends "score/layout.html" %}
{% load static %}

{% block body %}
{% if user.is_authenticated %}


<div class="container">

    {% for post in score %}
        {%if  forloop.first  %}
            <h2>Scores for: {{ request.user|title }} </h2>
        {% endif %}
    {% endfor %}
    <div class="table-responsive">
        <table class="table table-hover table-sm">
        <thead class="thead-dark">
            <tr>
            <th scope="col">Round</th>
            <th scope="col">Bowtype</th>
            <th scope="col">Score</th>
            <th scope="col">Classification</th>
            <th scope='col'>Handicap</th>
            <th scope="col">Date Shot</th>
            <th scope="col">Scorecards</th>
            </tr>
        </thead>
        <tbody>
        {% for post in score %}
            {% if  user.id  ==  post.archer_id  %} 
            <tr>
            <td class="align-middle">{{ post.rndname}} {{ post.classindex }}</td>
            <td class="align-middle">{{ post.bowtype }}</td>
            <td class="align-middle">{{ post.score }}</td>
            
            <td class="align-middle">{{ post.classification }}</td>
            <td class="align-middle">{{ post.handicap }}</td>           
            <td class="align-middle">{{ post.dateshot | date:"D d M Y"}}</td>
            <td> <h5><a class="btn btn-outline-dark btn-block btn-sm" href="{% url 'score:addscorecard' post.id %}">Add Score</a></h5>
            <h5><a class="btn btn-outline-dark btn-block btn-sm" href="{% url 'score:readscorecard' post.id %}">Read Score</a></h5></td>
            </tr>
            {% endif %}

            
        </tbody>
        {% endfor %}

        </table>
    </div>
</div>
{% else %}

My Scores

{% endif %}

{% endblock %}

archeryscorepad/score/templates/score/registration.html
{% extends "score/layout.html" %}
{% load crispy_forms_tags %}


{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block body %}
<div class="container">
    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'score:registration' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-12">
                {{ form.username|as_crispy_field }}
            </div>
        </div>
        <div class="row">  
            <div class="col-6">
            {{ form.first_name|as_crispy_field }}
            </div> 

            <div class="col-6">
            {{ form.last_name|as_crispy_field }}
            </div>
        </div>         
        <div class="row">
            <div class="col-6">
                {{ form.DoB|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.gender|as_crispy_field }}
            </div> 
        </div>
        <div class="row">
            <div class='col-6'>
                {{ form.club|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.email|as_crispy_field }}
            </div> 
        </div>
        <div class="row">  
            <div class="col-6">
            {{ form.password1|as_crispy_field }}
            {{ form.password.errors}}
            </div>
            <div class="col-6">
            {{ form.password2|as_crispy_field }}
            </div>
        </div>
        <div>
       <input class="btn btn-primary" type="submit" value="Register">
        </div>
        </form>
        <br>
        <div>
        Already have an account? <a href="{% url 'score:login' %}">Log In here.</a>
        </div>  
        </div>


    

{% endblock %}